# Generated by Django 3.1.6 on 2021-02-25 11:49

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20210225_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 25, 11, 49, 30, 266722, tzinfo=utc)),
        ),
    ]
