# Generated by Django 3.1.6 on 2021-02-26 10:59

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_auto_20210226_1043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 26, 10, 59, 29, 91842, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
