# Generated by Django 3.0.3 on 2021-04-30 11:34

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_auto_20210430_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='author',
            field=models.CharField(default='neel', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comments',
            name='slug',
            field=models.CharField(default=123, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 11, 34, 1, 769729, tzinfo=utc)),
        ),
    ]
