# Generated by Django 3.0.3 on 2021-04-30 12:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20210430_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 4, 30, 12, 23, 10, 788835, tzinfo=utc)),
        ),
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
