# Generated by Django 3.0.3 on 2021-05-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0034_auto_20210504_1548'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comments',
        ),
    ]
