# Generated by Django 3.0.3 on 2021-05-05 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0037_likes'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Likes',
        ),
    ]
