# Generated by Django 3.0.3 on 2021-05-11 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0042_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='likes',
        ),
    ]
