# Generated by Django 3.0.3 on 2021-05-11 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0046_auto_20210511_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='media/images/default.jpg', null=True, upload_to='media/images/'),
        ),
    ]
