# Generated by Django 3.0.3 on 2021-05-11 11:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0050_auto_20210511_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='comments',
            name='score',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
