# Generated by Django 3.0.3 on 2021-05-12 04:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0051_comments_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='score',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(0)]),
        ),
    ]
