# Generated by Django 3.0.3 on 2021-05-12 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0054_auto_20210512_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='text',
            field=models.CharField(max_length=300),
        ),
    ]
