# Generated by Django 3.1.6 on 2021-02-23 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20210223_0825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 9, 38, 52, 220478, tzinfo=utc)),
        ),
    ]
