# Generated by Django 3.1.6 on 2021-02-23 10:15

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20210223_0938'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, default=datetime.datetime(2021, 2, 23, 10, 15, 11, 811689, tzinfo=utc), primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 10, 14, 9, 529839, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(default=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 10, 14, 9, 529839, tzinfo=utc)), max_length=200, unique=True),
        ),
    ]
