# Generated by Django 3.1.6 on 2021-02-23 10:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20210223_1015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_on',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 10, 16, 50, 450781, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.DateTimeField(default=models.DateTimeField(default=datetime.datetime(2021, 2, 23, 10, 16, 50, 450781, tzinfo=utc)), max_length=200, unique=True),
        ),
    ]
